### ISSUE TITLE
Использование GIF вместо MP4

### ISSUE THREAD

**Issue by zhovner** [93rus/CV#1]
На сайте https://93rus.github.io/CV/ используются 2 GIF-файла общим размером больше 1,5МБ. Формат GIF устарел, намного правильнее использовать MP4 (h264). Это позволит в несколько раз уменьшить размер файлов. 

Пример можно посмотреть здесь https://slozhno.media

Прошу в кратчайшие сроки исправить данный косяк.

**Comment by 93rus** [comment]
Спс, исправлено. :)
